name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK & sbt
      uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java-version }}

    - name: Run tests
      run: |
        sbt headerCheck
        sbt ^test
        sbt ^mimaReportBinaryIssues
